version: '3.7'

services:
  apiproject:
      build:
        context: ../..
      ports:
        - 8080:8080
      volumes:
        - ../../config.yml:/etc/config.yaml
        - ../../ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      networks:
        - db
      depends_on:
        - db
      restart: on-failure
  db:
    container_name: db
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=rss
      - POSTGRES_PASSWORD=rss
      - POSTGRES_DB=rss
    ports:
      - "5432:5432"
    volumes:
      - ../../db/migrations/001.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db

networks:
  db:
    driver: bridge